# Add your secrets here for Streamlit Cloud
OPENAI_API_KEY = "k-proj-WWf6LFPCy-5PkfFYA51UkvABkD7Qh7WpN3gEAnWOrAVlGFshb8bs9p-nnRiohqe0-KI63KcS9KT3BlbkFJ-O_sPWv-dKsd28FT12UMIzoC_w7UDhOrlpyEYcz3eZt4KAAqSd5xnfWvgHZqCjQVUk3PSN6k8A"
TMDB_API_KEY = "f1b77659d995602b064f3a2d7137b424"
